name = "EPSpectral"
uuid = "156663f6-0b4c-4138-975b-20c69cfd5e8b"
authors = ["Jae-Mo Lihm <jaemolim96@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ElectronPhonon = "06c0995b-90c7-4aad-a219-585912522888"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[sources]
ElectronPhonon = {url = "https://github.com/jaemolihm/ElectronPhonon.jl", rev = "main"}

[compat]
OhMyThreads = "0.7, 0.8"
julia = "1.11"

[extras]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Interpolations", "Pkg", "Test"]
